cc_binary(
    name = "memcpy",
    srcs = ["memcpy.cc", "benchmark.h"],
)

cc_binary(
    name = "performance",
    srcs = ["performance.cc", "benchmark.h"],
    deps = ["//builder", "//runtime"],
)
