name: pages
on:
  pull_request:
  push:
    tags:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          gcc: '11'

      - name: Generate visualizations
        run: bazel test -c opt builder:pipeline_test
        
      - name: Extract visualizations
        run: |
          rf -rf /tmp/slinky_viz
          mkdir /tmp/slinky_viz
          unzip bazel-testlogs/builder/pipeline_test/test.outputs/outputs.zip -d /tmp/slinky_viz
          ls -l  /tmp/slinky_viz


